steps:
  # サーバーテスト
  - name: gcr.io/$PROJECT_ID/docker-compose
    args:
      - "-f"
      - "compose.yml"
      - "-f"
      - "compose.test.yml"
      - "up"
      - "server"
  - name: gcr.io/$PROJECT_ID/docker-compose
    args:
      - "-f"
      - "compose.yml"
      - "-f"
      - "compose.test.yml"
      - "up"
      - "web-front"

  # サーバー
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/dynamic-diary-server:$COMMIT_SHA"
      - "-f"
      - "./server/Dockerfile"
      - "--target"
      - "prod"
      - "./server"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/dynamic-diary-server:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "dynamic-diary-server"
      - "--image"
      - "gcr.io/$PROJECT_ID/dynamic-diary-server:$COMMIT_SHA"
      - "--region"
      - "asia-northeast2"

  # フロント
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/dynamic-diary-web-front:$COMMIT_SHA"
      - "-f"
      - "./web-front/Dockerfile"
      - "--target"
      - "runner"
      - "./web-front"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/dynamic-diary-web-front:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "dynamic-diary-web-front"
      - "--image"
      - "gcr.io/$PROJECT_ID/dynamic-diary-web-front:$COMMIT_SHA"
      - "--region"
      - "asia-northeast2"

images:
  - "gcr.io/$PROJECT_ID/dynamic-diary-server:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/dynamic-diary-web-front:$COMMIT_SHA"
