steps:
  # サーバーテスト
  - name: gcr.io/$PROJECT_ID/docker-compose
    args:
      - run
      - -e
      - GOOGLE_CREDENTIAL=$_GOOGLE_CREDENTIAL
      - FIREBASE_TEST_UID=$_FIREBASE_TEST_UID
      - FIRESTORE_EMULATOR_HOST=$_FIRESTORE_EMULATOR_HOST
      - FIREBASE_AUTH_EMULATOR_HOST=$_FIREBASE_AUTH_EMULATOR_HOST
      - server
      - go
      - test
      - ./...
    id: server-test

  # フロントテスト
  - name: gcr.io/$PROJECT_ID/docker-compose
    args:
      - run
      - web-front
      - yarn
      - test
    id: web-front-test
    waitFor:
      - -
