steps:
  # サーバーテスト
  - name: gcr.io/$PROJECT_ID/docker-compose
    args:
      - "-f"
      - "compose.yml"
      - "-f"
      - "compose.test.yml"
      - "up"
      - "server"
    id: "server-test"

  # フロントテスト
  - name: gcr.io/$PROJECT_ID/docker-compose
    args:
      - "-f"
      - "compose.yml"
      - "-f"
      - "compose.test.yml"
      - "up"
      - "web-front"
    id: "web-front-test"
    waitFor:
      - "-"
