steps:
  # サーバーテスト
  - name: gcr.io/$PROJECT_ID/docker-compose
    args:
      - "-f"
      - "compose.yml"
      - "-f"
      - "compose.test.yml"
      - "run"
      - "server"
      - "go"
      - "test"
      - "./..."
    id: "server-test"

  # フロントテスト
  - name: gcr.io/$PROJECT_ID/docker-compose
    args:
      - "-f"
      - "compose.yml"
      - "-f"
      - "compose.test.yml"
      - "run"
      - "web-front"
      - "yarn"
      - "test"
    id: "web-front-test"
    waitFor:
      - "-"
