services:
  firebase:
    build:
      context: firebase
    volumes:
      - ./firebase:/opt/workspace:cached
    ports:
      - 9099:9099
      - 4000:4000
      - 4400:4400
      - 4500:4500
      - 8082:8082
    environment:
      USE_LOCAL_BACKEND: 1
    working_dir: /opt/workspace

  server:
    build:
      context: server
      target: dev
    volumes:
      - ./server:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - firebase

  web-front:
    build:
      context: web-front
      target: dev
    volumes:
      - ./web-front:/app
    ports:
      - 3000:3000
